# Generated by Django 5.2.1 on 2025-05-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_remove_post_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='caption',
        ),
    ]
