# Generated by Django 5.2.1 on 2025-06-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_post_caption_post_excerpt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Community',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='community',
        ),
    ]
